version: "3"
services:
  tg-gpt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tg-gpt
    restart: always
    privileged: true
    dns:
      - 1.1.1.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - BOT_TOKEN=${BOT_TOKEN?:err}
      - OPENAI_TOKEN=${OPENAI_TOKEN?:err}
      - YA_TOKEN=${YA_TOKEN?:err}